# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5da71044a79c9381c943efb1d35fc148b08f034a023eaa2849fea5ccca1923afd476fa488f19a8c640162c34df4db0c5a1f3826c7edca30e3207fc062f64048

test:
  secret_key_base: 7614c933a11b877eaf417a358bf376577b23b70a2ff57e9996cda569ba45d457e67d03c0d561118b05b9ce88148c72442b36dd95a224d69a534daf30c98226ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
